version: "3.7"

services:
  igibson:
    image: docker.io/igibson/igibson:${VERSION}
    build:
      context: ./igibson
      dockerfile: Dockerfile

  igibson-vnc:
    image: docker.io/igibson/igibson-vnc:${VERSION}
    build:
      context: ./igibson
      dockerfile: Dockerfile

  igibson-tensorflow:
    image: docker.io/igibson/igibson-tensorflow:${VERSION}
    build:
      context: ./tensorflow
      dockerfile: Dockerfile
