name: Remove old artifacts

on:
  workflow_dispatch:
  schedule:
    # Every day at 1am PT
    - cron: '0 9 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Delete everything
